title: 'site-title'
# email: your-email@domain.com
description: >
  This is Cookies.
google_analytics: 'UA-86972045-2'

markdown: kramdown
gems:
exclude:
  - Gemfile
  - Gemfile.lock

timezone: Asia/Tokyo

auto: true
server: true
